version: '3.8'

services:
  cli:
    build: .
    container_name: ccip-nft-bridge-cli
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    tty: true
    stdin_open: true
    working_dir: /usr/src/app
    command: tail -f /dev/null
